In [1]:
import tensorflow as tf

In [47]:
# physical_devices = tf.config.list_physical_devices('CPU')
# tf.config.experimental.set_memory_growth(physical_devices[0], True)

In [3]:
# x = tf.constant(4, shape=(2, 2), dtype=tf.float32)
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [12]:
# x = tf.ones((3,3))
# x = tf.zeros((2,3))
# x = tf.eye(4)
# x = tf.random.normal((3,3), mean=0, stddev=1) # stddev - standard normal distribution
# x = tf.random.uniform((1,3), minval=0, maxval=10)
# x = tf.range(7)
# x = tf.range(start=1, limit=10, delta=2)
x = tf.cast(x, dtype=tf.float32) # convert between different types
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


#### Mathematical Operations

In [25]:
x = tf.constant([1,3,5])
y = tf.constant([9,7,5])
a = tf.constant([[4,2,6], [2,3,7]])

# z = tf.add(x, y) # z = x + y
# z = tf.subtract(y, x) # z = y - x
# z = tf.divide(y, x) # z = y / x
# z = tf.multiply(x, y) # z = x * y
# z = tf.tensordot(x, y, axes=1) #-------------
# z = tf.reduce_sum(a, axis=1) # 4 + 2 + 6 | 2 + 3 + 7
# z = tf.reduce_sum(a, axis=0) # 4 + 2 | 2 + 3 | 6 + 7
z = x ** 3
print(z)

tf.Tensor([  1  27 125], shape=(3,), dtype=int32)


In [41]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

print(x)
print(y)

z = tf.matmul(x, y) # z = x @ y #--------------
print(z)

tf.Tensor(
[[-1.1867114   0.08635858  2.0301428 ]
 [-1.7596318  -1.081399   -0.5300477 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-0.52714735 -0.22952862  2.6501021   0.5113372 ]
 [ 0.7046481   0.3680622  -0.73455167 -2.1764154 ]
 [ 2.1500032   0.30819    -0.18942632  0.20797904]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[ 5.0512376   0.92983925 -3.5929039  -0.37253475]
 [-0.9740248  -0.15749164 -3.7684553   1.3435693 ]], shape=(2, 4), dtype=float32)


In [65]:
x = tf.constant([0, 1, 1, 2, 1, 3, 2, 3])

indices = tf.constant([0, 3, 4])
x_ind = tf.gather(x, indices)

print(x_ind)

tf.Tensor([0 2 1], shape=(3,), dtype=int32)


In [70]:
x = tf.range(9)
print(x)
x = tf.reshape(x, (3, 3))
print(x)
x = tf.transpose(x, perm=[1, 0]) # column --> <-- row
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
